# Generated by Django 4.2.7 on 2025-11-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'User Logout'), ('FILE_UPLOADED', 'File Uploaded'), ('FILE_DOWNLOADED', 'File Downloaded'), ('FILE_SHARED', 'File Shared'), ('FILE_DELETED', 'File Deleted'), ('SHARE_REVOKED', 'Share Revoked'), ('ROLE_CHANGED', 'User Role Changed'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('PASSWORD_CHANGED', 'Password Changed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('SECURITY_ALERT', 'Security Alert'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='audit_audit_severit_34f2e8_idx'),
        ),
    ]
